# Artificial Neural Network

### Importing the libraries

In [6]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [7]:
tf.__version__

'2.0.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [8]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [9]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [10]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [12]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [14]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [17]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [18]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [19]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [20]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [21]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [22]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Train on 8000 samples
Epoch 1/100
8000/8000 [==============================] - 2s 270us/sample - loss: 0.5187 - accuracy: 0.7960
Epoch 2/100
8000/8000 [==============================] - 1s 76us/sample - loss: 0.4584 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 73us/sample - loss: 0.4347 - accuracy: 0.8029
Epoch 4/100
8000/8000 [==============================] - 1s 65us/sample - loss: 0.4240 - accuracy: 0.8141
Epoch 5/100
8000/8000 [==============================] - 1s 66us/sample - loss: 0.4186 - accuracy: 0.8200
Epoch 6/100
8000/8000 [==============================] - 1s 65us/sample - loss: 0.4130 - accuracy: 0.8234
Epoch 7/100
8000/8000 [==============================] - 1s 68us/sample - loss: 0.4075 - accuracy: 0.8265
Epoch 8/100
8000/8000 [==============================] - 1s 66us/sample - loss: 0.4007 - accuracy: 0.8275
Epoch 9/100
8000/8000 [==============================] - 1s 66us/sample - loss: 0.3946 - accuracy: 0.8300
Epoch 10/100
8000/8000 

8000/8000 [==============================] - 1s 64us/sample - loss: 0.3361 - accuracy: 0.8621
Epoch 78/100
8000/8000 [==============================] - 1s 67us/sample - loss: 0.3352 - accuracy: 0.8634
Epoch 79/100
8000/8000 [==============================] - 1s 65us/sample - loss: 0.3361 - accuracy: 0.8616
Epoch 80/100
8000/8000 [==============================] - 1s 65us/sample - loss: 0.3358 - accuracy: 0.8637
Epoch 81/100
8000/8000 [==============================] - 1s 64us/sample - loss: 0.3357 - accuracy: 0.8626
Epoch 82/100
8000/8000 [==============================] - 1s 65us/sample - loss: 0.3351 - accuracy: 0.8620
Epoch 83/100
8000/8000 [==============================] - 1s 65us/sample - loss: 0.3355 - accuracy: 0.8635
Epoch 84/100
8000/8000 [==============================] - 1s 64us/sample - loss: 0.3352 - accuracy: 0.8644
Epoch 85/100
8000/8000 [==============================] - 1s 64us/sample - loss: 0.3355 - accuracy: 0.8631
Epoch 86/100
8000/8000 [==========================

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

In [23]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


### Predicting the Test set results

In [24]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1505   90]
 [ 188  217]]


0.861